- type: custom-api
  title: Mensa - Heute
  cache: 1h
  url: "http://glance-api:3000/mensa/${MENSA_ID}"
  allow-insecure: true
  template: |
    <ul class="list">
    {{ range .JSON.Array ""}}
      {{ if and (ne ( .String "category" ) "Fleischgericht" ) }}
      <li class="card p-6">
        <p class="size-h4 color-positive block text-truncate">{{ .String "name" }}</p>
        <p class="size-small color-muted">{{ .String "category" }}</p>

        <ul class="list-horizontal-text mt-4">
          <li><strong>Studierende:</strong> {{ .String "prices.students" }} €</li>
        </ul>

        <div class="mt-4">
          <p class="size-small color-muted">Allergene / Hinweise:</p>
          <ul class="list-horizontal-text">
            {{ range .Array "notes" }}
              <li>{{ .String "" }}</li>
            {{ end }}
          </ul>
        </div>
      </li>

      {{ end }}
    {{ end }}
    </ul>


