services:
  mensa-glance-api:
    image: ghcr.io/AimPizza/my-glance-config:latest
    container_name: mensa-glance-api
    hostname: glance-api
    restart: unless-stopped
    networks:
      - internal_net
    expose:
      - 3000
    ports:
      - "3000:3000"
networks:
  traefik_proxy:
    external: true
  internal_net:
    driver: bridge
