services:
  mensa-glance-api:
    image: ghcr.io/aimpizza/glance-additions:latest
    # build: . # for local development
    container_name: mensa-glance-api
    hostname: glance-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"

  ## optional example - for local development
  # glance:
  #   container_name: glance
  #   image: glanceapp/glance
  #   restart: unless-stopped
  #   volumes:
  #     - ../config:/app/config
  #   ports:
  #     - 8081:8080
